spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        # Optimización de memoria para Hibernate
        hibernate.jdbc.batch_size: 20
        hibernate.order_inserts: true
        hibernate.order_updates: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    root: INFO
    com.david.inventory: INFO
    org.flywaydb: INFO
